import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

import {
  closeValidator,
  faqItemValidator,
  guaranteeValidator,
  heroValidator,
  howItWorksStepValidator,
  offerValidator,
  pageStatusValidator,
  pageTemplateValidator,
  problemValidator,
  serviceItemValidator,
  testimonialValidator,
  thankYouValidator,
  themeValidator,
  urgencyValidator,
  wedgeValidator,
} from "./lib/validators";

export default defineSchema({
  landingPages: defineTable({
    slug: v.string(),
    name: v.string(),
    status: pageStatusValidator,
    template: pageTemplateValidator,
    seoTitle: v.string(),
    seoDescription: v.string(),
    businessName: v.string(),
    phone: v.string(),
    serviceAreas: v.array(v.string()),
    offerText: v.string(),
    ctaLabel: v.string(),
    hero: heroValidator,
    problem: problemValidator,
    wedge: wedgeValidator,
    services: v.array(serviceItemValidator),
    howItWorks: v.array(howItWorksStepValidator),
    faq: v.array(faqItemValidator),
    testimonials: v.array(testimonialValidator),
    metaPixelId: v.optional(v.string()),
    googleAdsId: v.optional(v.string()),
    googleConversionLabel: v.optional(v.string()),
    leadServiceType: v.string(),
    surfaceOptions: v.array(v.string()),
    theme: v.optional(themeValidator),
    offer: v.optional(offerValidator),
    guarantee: v.optional(guaranteeValidator),
    urgency: v.optional(urgencyValidator),
    close: v.optional(closeValidator),
    thankYou: v.optional(thankYouValidator),
    servicesSectionTitle: v.optional(v.string()),
    servicesSectionDescription: v.optional(v.string()),
    gallerySectionTitle: v.optional(v.string()),
    gallerySectionDescription: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_slug", ["slug"]),

  landingPageGallery: defineTable({
    pageId: v.id("landingPages"),
    sortOrder: v.number(),
    label: v.optional(v.string()),
    beforeStorageId: v.id("_storage"),
    afterStorageId: v.id("_storage"),
  }).index("by_pageId", ["pageId"]),
});
